#!/usr/bin/env bash
#  Bash script that displays the content of the file '/etc/passwd'
# 	Your script should only display:
# 		username
# 		user id
# 		Home directory path for the user

while IFS=':' read -r username user_id home_dir
do
	echo "$username:$user_id:$home_dir"
done < /etc/passwd
