#!/bin/bash
# bash script that displays:
# 	the content of the current directory
# 	in list format
# 	Where only the part of the name after the first dash is displayed

for file in *; do
    if [[ -f "$file" ]]; then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
