#!/bin/bash
# bash script that displays:
# 	the content of the current directory
# 	in list format
# 	Where only the part of the name after the first dash is displayed

for file in *
do
    echo "$file" | cut -d'-' -f2
done
